[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jamf-resource-deleter"
version = "0.4.4"
description = "A module that reads JSON files of Jamf resources (IDs) and deletes them"
readme = "README.md"
authors = [{name = "Gordon Deacon", email = "gdeacon99@gmail.com"}]
license = {text = "Apache 2.0"}
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "jamfpy"
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/macdeacon99/jamfpro-resource-deleter"

[project.optional-dependencies]
dev = [
  "pytest",
  "ruff",
  "mypy",
  "bandit",
  "build"
]

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true